version: '3'

services:
  docker-app:
    image: allergy-api:0.0.1-SNAPSHOT
    environment:
      POSTGRES_HOST: postgres
      RABBIT_HOST: rabbitmq
      JAEGER_HOST: jaeger
    ports:
      - "8080:8080"